CREATE TABLE `users` (`facilityCode` VARCHAR , `facilityName` VARCHAR , `password` VARCHAR , `userFirstName` VARCHAR , `userLastName` VARCHAR , `username` VARCHAR , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )
CREATE TABLE `program` (`programCode` VARCHAR , `programName` VARCHAR , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY )
CREATE TABLE `products` (`code` VARCHAR , `primaryName` VARCHAR , `program_id` BIGINT , `strength` VARCHAR , `type` VARCHAR , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )
CREATE TABLE `stock_cards` (`expireDates` VARCHAR , `product_id` BIGINT UNIQUE, `stockOnHand` BIGINT , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )
CREATE TABLE `stock_items` (`documentNumber` VARCHAR , `movementDate` VARCHAR NOT NULL , `stockCard_id` BIGINT , `movementType` VARCHAR , `reason` VARCHAR ,`movementQuantity` BIGINT , `stockOnHand` BIGINT , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )
CREATE TABLE `rnr_forms` (`comments` VARCHAR , `periodBegin` VARCHAR , `periodEnd` VARCHAR , `program_id` BIGINT , `status` VARCHAR DEFAULT 'DRAFT' , `synced` SMALLINT , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )
CREATE TABLE `rnr_baseInfo_items` (`name` VARCHAR , `rnRForm_id` BIGINT , `type` VARCHAR , `value` VARCHAR , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )
CREATE TABLE `rnr_form_items` (`validate` VARCHAR , `approvedAmount` BIGINT , `requestAmount` BIGINT , `form_id` BIGINT , `product_id` BIGINT , `inventory` BIGINT , `issued` BIGINT , `initialAmount` BIGINT , `received` BIGINT , `calculatedOrderQuantity` BIGINT , `adjustment` BIGINT , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )
CREATE TABLE `regimes` (`code` VARCHAR PRIMARY KEY, `name` VARCHAR , `type` VARCHAR , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER)
CREATE TABLE `regime_items` (`amount` BIGINT , `form_id` BIGINT , `regimen_code` VARCHAR , `createdAt` VARCHAR NOT NULL , `updatedAt` VARCHAR NOT NULL , `id` INTEGER PRIMARY KEY AUTOINCREMENT )

CREATE UNIQUE INDEX `users_id_idx` ON `users` ( `id` )
CREATE UNIQUE INDEX `program_id_idx` ON `program` ( `id` )
CREATE UNIQUE INDEX `products_id_idx` ON `products` ( `id` )
CREATE UNIQUE INDEX `stock_cards_id_idx` ON `stock_cards` ( `id` )
CREATE UNIQUE INDEX `stock_items_id_idx` ON `stock_items` ( `id` )
CREATE UNIQUE INDEX `rnr_forms_id_idx` ON `rnr_forms` ( `id` )
CREATE UNIQUE INDEX `rnr_baseInfo_items_id_idx` ON `rnr_baseInfo_items` ( `id` )
CREATE UNIQUE INDEX `rnr_form_items_id_idx` ON `rnr_form_items` ( `id` )
CREATE UNIQUE INDEX `regimes_id_idx` ON `regimes` ( `code` )
CREATE UNIQUE INDEX `regime_items_id_idx` ON `regime_items` ( `id` )